export const permissionsOptions = [
    { label: "Usuario Administrador", value: "admin_user" },
    { label: "Crear usuario", value: "create_user" },
    { label: "Actualizar usuario", value: "update_user" },
    { label: "Eliminar usuario", value: "delete_user" },
    { label: "Ver usuarios", value: "view_users" },
    { label: "Ver usuario", value: "view_user" },
    { label: "Crear puesto", value: "create_role" },
    { label: "Actualizar puesto", value: "update_role" },
    { label: "Eliminar rol", value: "delete_role" },
    { label: "Ver puestos", value: "view_roles" },
    { label: "Ver puesto", value: "view_role" },
    { label: "Crear departamento", value: "create_department" },
    { label: "Actualizar departamento", value: "update_department" },
    { label: "Eliminar departamento", value: "delete_department" },
    { label: "Ver departamentos", value: "view_departments" },
    { label: "Ver departamento", value: "view_department" },
    { label: "Crear guion", value: "create_script" },
    { label: "Actualizar guion", value: "update_script" },
    { label: "Eliminar guion", value: "delete_script" },
    { label: "Ver guiones", value: "view_scripts" },
    { label: "Ver guion", value: "view_script" },
    { label: "Crear nota", value: "create_content" },
    { label: "Actualizar nota", value: "update_content" },
    { label: "Eliminar nota", value: "delete_content" },
    { label: "Ver notas", value: "view_contents" },
    { label: "Ver nota", value: "view_content" },
    { label: "Crear Boletín", value: "create_newsletter" },
    { label: "Actualizar Boletín", value: "update_newsletter" },
    { label: "Eliminar Boletín", value: "delete_newsletter" },
    { label: "Ver Boletines", value: "view_newsletters" },
    { label: "Ver Boletín", value: "view_newsletter" },
    { label: "Verificar estado de autenticación", value: "check_auth_status" },
];